name: Sylvedex

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: window-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm
      - run: npm run build
