export { type AbilityResource } from './ability/ability-resource';
export { type BaseEntity } from './shared/base-entity';
export { type NamedApiResourceList } from './shared/named-api-resource-list';
export { type ApiResource } from './shared/api-resource';
export { type Pokemon } from './pokemon/pokemon';
export { type PokemonType } from './pokemon/pokemon-type';
export { type Sprite } from './pokemon/sprite';
export { type Stat } from './pokemon/stat';
export { type Type, type TypeRelations, type TypePokemon } from './type/type';
export { fallbackNamedApiResource, type NamedApiResource } from './shared/named-api-resource';
export { fallbackEffect, type Effect } from './effect/effect';
export { fallbackAbilityEffectChange, type AbilityEffectChange } from './ability/ability-effect-change';
export { fallbackVerboseAbilityEffect, type VerboseAbilityEffect } from './ability/verbose-ability-effect';
export { fallbackAbility, type Ability } from './ability/ability';
export { type EvolutionChain } from './evolution/evolution-chain';
export { type ChainLink } from './evolution/chain-link';
export { type EvolutionDetail } from './evolution/evolution-detail';
export { type EvolutionTrigger } from './evolution/evolution-trigger';
export { type Item } from './item/item';
export { type ItemSprite } from './item/item-sprite';
export { type PokemonSpecies } from './pokemon/pokemon-species';
