name: Sylvedex

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '18'
    steps:
      - uses: actions/checkout@v1
      - run: npm
      - run: npm run build
      - uses: ./.github/workflows/dev.workflow.yml
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'dist'
